---
- name: "Setup chrony configuration"
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: "{{ chrony_file_conf }}"
    backup: "{{ chrony_backup }}"
    owner: root
    group: root
    mode: 0640
  notify:
    - restart chrony
