---
# tasks file for chrony

- name: "Add the OS specific varibles"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "os-{{ ansible_distribution }}.yml"
    - "os-default.yml"
  tags:
    - always

# Debian(setup) specific tasks
- name: "Include packages tasks"
  ansible.builtin.include_tasks:
    file: packages-{{ ansible_os_family }}.yml
    apply:
      tags:
        - chrony
        - chrony:setup
  tags:
    - always

# Common configuration tasks tasks
- name: "Include config tasks"
  ansible.builtin.include_tasks:
    file: config.yml
    apply:
      tags:
        - chrony
        - chrony:config
  tags:
    - always

# Common service tasks
- name: "Include service tasks"
  ansible.builtin.include_tasks:
    file:  service.yml
    apply:
      tags:
        - chrony
        - chrony:service
  tags:
    - always