---
- name: "RedHat | check packages"
  ansible.builtin.yum:
    pkg: "{{ package.name }}"
    state: "{{ package.state }}"
  with_items: "{{ chrony_packages }}"
  loop_control:
    loop_var: package
