---
- name: "Ensure chrony started/stopped"
  ansible.builtin.service:
    name: "{{ chrony_service }}"
    state: "{{ chrony_service_state }}"
    enabled: "{{ chrony_service_enabled }}"
  when: not chrony_test
